# analytics-engineering/Dockerfile.duckdb
FROM python:3.11-slim

# Install uv
RUN pip install --no-cache-dir uv

# Install dbt and duckdb using uv
RUN uv pip install --system --no-cache \
    dbt-core \
    dbt-duckdb \
    dbt-postgres \
    duckdb \
    jupyter \
    pandas \
    numpy

# Create a directory for dbt
WORKDIR /workspace

RUN apt-get update && apt-get install -y git
ENV DBT_PROFILES_DIR=/workspace

# Default command
CMD ["/bin/bash"]